### ISSUE TITLE
Missing <th> in <thead> displays undifined when it has been stacktable

### ISSUE THREAD

**Issue by jacquesletesson** [johnpolacek/stacktable.js#1]
I have a table with four `<th>` in the `<thead>`, however I got only four columns in my table.

When I use stacktable, the missing `<th>` is populated with the word undifined.

To fix this issue (in my case), I just tweak your code a little bit : 

```javascript
if ($topRow.find('td,th').eq(index).html()){
  markup += '<td class="st-key">'+$topRow.find('td,th').eq(index).html()+'</td>';
 } else {
  markup += '<td class="st-key"></td>';
}
```

Thanks for the great plugin.

J.

**Comment by Lechus** [comment]
+1.
Could you add option for td in thead?
