### ISSUE TITLE
Document the minimum jQuery version

### ISSUE THREAD

**Issue by OxideInteractiveDev** [johnpolacek/stacktable.js#20]
Document the minimum jQuery version.

**Comment by frob** [comment]
++ this

I'm thinking 1.6, but I haven't looked to deeply into it.

**Comment by akalata** [comment]
https://github.com/johnpolacek/stacktable.js/blob/master/stacktable.jquery.json specifies > 1.8.1, are you saying that this is incorrect?

**Comment by frob** [comment]
I cannot find anything that would require 1.8 or greater than 1.6.

What we are saying is that it isn't specifically documented.

**Comment by akalata** [comment]
```javascript
    "dependencies": {
        "jquery": ">=1.8.1"
    }
```
This is in stacktable.jquery.json.

**Comment by frob** [comment]
I question its accuracy, and that is not documentation.
