### ISSUE TITLE
windows phone - no effect ?

### ISSUE THREAD

**Issue by pepperstreet** [johnpolacek/stacktable.js#31]
Hello, came here from a Drupal Commerce article about responsive checkout tables... 
I can't see any effect on your project website and demo. Apart from that, the site itself is not responsive?! Any clues? 

Currenrly I am using a windows phone. 53x series.

**Comment by johnpolacek** [comment]
You need to click the blue run>> link to see the effect get applied to the first example. If you scroll down, the other examples are applied automatically. I don't have a windows phone to test on so please attach a screenshot if it doesn't match what you see when you go to the demo on a desktop with the window matching your phone screen width.
