### ISSUE TITLE
click event don't goes up

### ISSUE THREAD

**Issue by drpark** [johnpolacek/stacktable.js#43]
Hi,
in my table I create some links with ids, and then some on click event with jquery with some ajax calls behind.

If stacktable is not here, everything works fine, but when i enable stackable , events seems to be lost and it don't work anymore

exemple hereunder the hello is never displayed is stacktable applied on the table, displayed if statcktable disabled.
thanks,
`<tr id="57d69a51-9b60-4c9f-9b92-e3a1ac112135" style="cursor: pointer; cursor: hand;">

```
                     <td>
                        <span id='np57d69a51-9b60-4c9f-9b92-e3a1ac112135'>Oui - <a href="/admin/repas/np/57d69a51-9b60-4c9f-9b92-e3a1ac112135" class="test" id="link-1282719413">Non pris</a></span>                        </td>
                    <td>
                        <span id='npc57d69a51-9b60-4c9f-9b92-e3a1ac112135'>Non</span>                        </td>

                </tr>
```

<script type="text/javasript">
    $( ".test" ).click(function() {
  alert('hello');
});
    
</script>

`

**Comment by johnpolacek** [comment]
Attach your event listener to the body instead.
$( "body" ).on("click",".test", function() { alert('hello'); });
