### ISSUE TITLE
CDN for stacktable is not reachable.

### ISSUE THREAD

**Issue by sathishjayapal** [johnpolacek/stacktable.js#47]
The https://files-stackablejs.netdna-ssl.com/stacktable.min.js CDN is not accesible., any thgts if you have plans to move to a different CDN or if it is already moved is it possible to update the new CDN location?? Cheers.

**Comment by johnpolacek** [comment]
Just checked and it seems to be up. Are you still having issues?

**Comment by sathishjayapal** [comment]
Seems to be working now. But I ended pulling the JS into local repo. Thanks.

**Comment by oskari** [comment]
CDN url seems to give 404 error now
