### ISSUE TITLE
License version confirmation

### ISSUE THREAD

**Issue by Piicksarn** [johnpolacek/stacktable.js#48]
Hi @johnpolacek  :raising_hand:
The issue is from [cdnjs](https://github.com/cdnjs/cdnjs), would you please provide the license version of GPL?
Cause we desired to include **stacktable.js** and follow https://spdx.org/licenses/ for license confirmation.

:point_right:  The related lib request from user to cdnjs is [here](https://github.com/cdnjs/cdnjs/issues/9486).
:point_right:  And related lib addition pull request is [here](https://github.com/cdnjs/cdnjs/pull/9711).

Thanks for your great work!!!!  :raised_hands:

Piicksarn

**Comment by johnpolacek** [comment]
Added License.txt file with MIT license. Work for you?

**Comment by Piicksarn** [comment]
It shows the lib follow dual MIT and GPL license.
I think MIT is fine so far, but GPL license need more information

**Comment by Piicksarn** [comment]
@johnpolacek,
So the library doesn't use GPL license?

**Comment by johnpolacek** [comment]
@Piicksarn 
Added GPL to the license file as well.

**Comment by Piicksarn** [comment]
@johnpolacek, thank you!!
