### ISSUE TITLE
Nested Table Fails

### ISSUE THREAD

**Issue by PieterEringa** [johnpolacek/stacktable.js#5]
When a table contains nested tables the stacktable.js fails. The data from nested tables is parsed into the stacked table. 

A possible solution: When parsing tables, check if  the table row and table data are children of the looped parent table and ignore when they are not.

JSFiddle: http://jsfiddle.net/ndrRH/

**Comment by kamdz** [comment]
@johnpolacek: you still accepting? ;)

**Comment by johnpolacek** [comment]
Yeah. I don't want to push any breaking changes but if you can add functionality or fix a bug that doesn't break the plugin for existing users, then I will gladly take a look. (Please be patient though as it might take me a day or 3 to get to it). Thanks!

**Comment by johnpolacek** [comment]
This is fixed now.
