### ISSUE TITLE
License version confirmation

### ISSUE THREAD

**Issue by sufuf3** [johnpolacek/stacktable.js#61]
Hi @johnpolacek 
We are cdnjs team, we're going to host this library.

Which license is this repository under? `GPL-3.0` or `LGPL-3.0`.
I saw the content of [License.txt](https://github.com/johnpolacek/stacktable.js/blob/master/License.txt#L24) is the same as [`LGPL-3.0`](https://spdx.org/licenses/LGPL-3.0). But I saw #48 this repo is under [`GPL-3.0`](https://spdx.org/licenses/GPL-3.0).

If you have any suggestions, please let me know.
Thank you.

cdnjs/cdnjs#11472

**Comment by sufuf3** [comment]
@johnpolacek Could you help me?
Thank you.

**Comment by johnpolacek** [comment]
I updated it to be MIT License. As far as I'm concerned, people are free to do whatever they want.

**Comment by sufuf3** [comment]
It's sound great.
Thank you very much.
